#!/bin/bash

bspc config border_width        5
bspc config window_gap         120
bspc config top_padding	       0

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc rule -a Gimp desktop=^7 follow=on state=floating
bspc rule -a Steam desktop=^9 state=floating follow=off
bspc rule -a feh state=floating focus=off
bspc rule -a Gifview state=floating focus=on
bspc rule -a qbittorrent desktop=^8

# Visual options
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

# Pink
bspc config normal_border_color "#777777"
bspc config active_border_color "#C6B5D6"
bspc config focused_border_color "#C6B5D6"

# Brown
#bspc config normal_border_color "#312210"
#bspc config active_border_color "#896B65"
#bspc config focused_border_color "#896B65"

#bspc config presel_border_color "#7F8C8D"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

rustabari | lemonbar -p -f $iconfont -f "Tewi:size=9" -g 1920x30 &
