[bar]
# Update interval, in seconds
update_interval = 5

separator = " | "
background = "#000000"
background_opacity = 40
foreground = "#dddddd"
# foreground_opacity = 100
wm = "bspwm"

[[module]]
align = "left"

    # Add padding
    [[module.block]]
    kind = "custom"
    command = "echo '   '"

[[module]]

    [[module.block]]
    kind = "workspaces"
    icon = "\uE001"
    active_icon = "\uE000"

[[module]]
align = "center"

    [[module.block]]
    kind = "title"
    max_chars = 75

[[module]]
align = "right"
separator = " | "

    [[module.block]]
    kind = "wifi"
    icons = ["\uE0F1", "\uE0F2", "\uE0F3"]
    icon_align = "left"
    device = "wlp2s0"

    [[module.block]]
    kind = "music"
    command = "mpc current"
    icon = "\uE1A6"
    icon_align = "left"

    [[module.block]]
    kind = "battery"
    # icon = "\uE1FF"
    icons = ["\uE1FD", "\uE1FE", "\uE1FF"]
    icon_align = "right"
    monitor_battery = true

    [[module.block]]
    kind = "date"
    format = "%a %b %d"
    icon = "\uE1CD"
    icon_align = "left"

    [[module.block]]
    kind = "date"
    format = "%I:%M %p"
    icon = "\uE015"
    icon_align = "left"

[[module]]

    # Padding
    [[module.block]]
    kind = "custom"
    command = "echo '   '"
